### ISSUE TITLE
Missing package declaration

### ISSUE THREAD

**Issue by LucyMcGowan** [yonicd/carbonate#2]
This is _awesome_! I love the new ability to add a tinyurl! I was just trying to run it and ran into a problem if I hadn't already loaded the **magick** package. I believe the problem is this line:

https://github.com/yonicd/carbonate/blob/33c12fae0d3979c3337411ff630ac2bd2b8c8757/R/carbonate.R#L75

I think it should be:

```
magick::image_write(file.path(path,file))
```

I'm happy to submit a quick PR, or if it would be easier for you to fix that is 👌 too!

**Comment by LucyMcGowan** [comment]
I also just realized there may be an issue with this chunk as well if the pipe isn't loaded:

https://github.com/yonicd/carbonate/blob/33c12fae0d3979c3337411ff630ac2bd2b8c8757/R/carbonate.R#L71-L77

**Comment by yonicd** [comment]
good catches. i thought i ran cmd check (oops). i'll update those. thanks :)

**Comment by yonicd** [comment]
thanks again! https://github.com/yonicd/carbonate/commit/7256fb03728ad6164c31b3039fa837e0b88d45cc
