### ISSUE TITLE
incomplete list of available templates

### ISSUE THREAD

**Issue by mike-lawrence** [yonicd/carbonate#25]
The `get_templates()` function appears to return an incomplete list of templates available at carbon.now.sh; for example, it doesn't include the "One Light" template.

**Comment by yonicd** [comment]
Thanks for the update. You can put in a PR if you have time. I will get to it in a few days if not.

here is where the lists of presets are located

https://github.com/yonicd/carbonate/blob/master/R/set_get_functions.R#L34_L55
