### ISSUE TITLE
Copy tinyurl to clipboard

### ISSUE THREAD

**Issue by LucyMcGowan** [yonicd/carbonate#3]
What do you think about a function that would let you either print the tinyurl or copy it to the clipboard (to include in a tweet)?

**Comment by yonicd** [comment]
you can build the tinyurl regardless of creating the image. you could grab that and pipe it into {twitteR}. (I didnt want to add any strong imports to the package)

saying that, if you have any ideas on improving upon the current workflow I think that would be great.

**Comment by yonicd** [comment]
sorry i take that back, it's a [private](https://github.com/yonicd/carbonate/blob/master/R/carbon.R#L267) method

**Comment by yonicd** [comment]
what i really wanted to do originally was add option to port the image directly to the clipboard and move it to a post, but I think that it is a bridge too far for clipr.

**Comment by yonicd** [comment]
here you go. you can test it out https://github.com/yonicd/carbonate/commit/429aad1bbec21cb48ad3eee2b48cdcae4fde7ebd before i PR it :)

**Comment by LucyMcGowan** [comment]
Just gave it a spin 🌀, looks great!

**Comment by yonicd** [comment]
Thanks for the idea.

**Comment by yonicd** [comment]
@LucyMcGowan  ==> [FYI](https://github.com/yonicd/carbonate/blob/rtweet/R/carbon_fields.R#L29_L32)
